// ============================================================
// ATTENDING AI - Clinical AI Branding & Disclaimer Constants
// apps/shared/lib/clinicalBranding.ts
//
// FDA / AMA / HIPAA Compliance:
// Clinical decision support (CDS) tools must clearly communicate
// that they are advisory, not autonomous decision-makers.
// 21 CFR Part 11 and ONC's CDS framework require that:
//   - The provider retains final clinical authority
//   - AI outputs are framed as suggestions, not directives
//   - Evidence sources are cited when available
//   - Limitations are disclosed
//
// All UI components rendering AI-generated clinical content
// should use these constants for consistent, compliant language.
// ============================================================

// ============================================================
// PRODUCT IDENTITY
// ============================================================

/** Product name as shown in clinical contexts */
export const PRODUCT_NAME = 'ATTENDING AI';

/** Product subtitle for clinical contexts */
export const PRODUCT_SUBTITLE = 'Evidence-Based Clinical Decision Support';

/** Short tagline */
export const PRODUCT_TAGLINE = 'Clinical intelligence, physician-directed.';

// ============================================================
// CLINICAL DISCLAIMERS
// ============================================================

/** Standard footer disclaimer for any AI-generated content */
export const CLINICAL_DISCLAIMER =
  'This information is generated by an evidence-based clinical decision support system. ' +
  'All suggestions require independent clinical judgment and verification by the treating provider. ' +
  'This system does not replace professional medical decision-making.';

/** Short inline disclaimer (for tight UI spaces) */
export const CLINICAL_DISCLAIMER_SHORT =
  'Clinical decision support — requires provider verification.';

/** Disclaimer for AI-generated differential diagnoses */
export const DIFFERENTIAL_DISCLAIMER =
  'Differential diagnoses are generated from evidence-based algorithms and clinical guidelines. ' +
  'They are intended to support, not replace, clinical reasoning. ' +
  'Consider patient-specific factors not captured in this analysis.';

/** Disclaimer for AI risk scores */
export const RISK_SCORE_DISCLAIMER =
  'Risk scores are derived from population-level models and published clinical criteria. ' +
  'Individual patient factors may not be fully represented. ' +
  'Clinical correlation is required.';

/** Disclaimer for treatment recommendations */
export const TREATMENT_DISCLAIMER =
  'Treatment suggestions are based on published clinical guidelines and formulary data. ' +
  'The prescribing provider is responsible for all treatment decisions, ' +
  'including consideration of patient allergies, contraindications, and preferences.';

/** Disclaimer for medication interactions */
export const INTERACTION_DISCLAIMER =
  'Drug interaction alerts are generated from pharmaceutical reference databases. ' +
  'Not all interactions may be detected. Clinical judgment should guide prescribing decisions.';

// ============================================================
// APPROVED TERMINOLOGY
// ============================================================
// Use these instead of autonomous/definitive AI language.
//
// ❌ AVOID                    → ✅ USE INSTEAD
// "AI diagnoses"              → "Clinical decision support suggests"
// "AI recommends treatment"   → "Evidence-based treatment options"
// "AI detected"               → "System flagged for review"
// "AI analysis shows"         → "Clinical analysis indicates"
// "AI-powered diagnosis"      → "Evidence-based diagnostic support"
// "AI risk prediction"        → "Risk stratification model"
// "Our AI found"              → "Decision support analysis"
// "the AI says"               → "Clinical guidelines suggest"
// "AI order recommendations"  → "Evidence-based order suggestions"
// ============================================================

export const TERM = {
  // Verbs — what the system does
  suggests: 'suggests for clinical consideration',
  flagged: 'flagged for provider review',
  indicates: 'indicates based on available evidence',
  identified: 'identified for clinical evaluation',

  // Nouns — what the system produces
  recommendation: 'evidence-based suggestion',
  recommendations: 'evidence-based suggestions',
  diagnosis: 'diagnostic consideration',
  diagnoses: 'differential considerations',
  riskScore: 'risk stratification score',
  alert: 'clinical alert',
  analysis: 'clinical analysis',
  insight: 'clinical insight',

  // Section headers
  aiInsightsHeader: 'Clinical Decision Support',
  aiRecommendationsHeader: 'Evidence-Based Suggestions',
  aiDiagnosisHeader: 'Diagnostic Considerations',
  aiRiskHeader: 'Risk Stratification',
  aiOrdersHeader: 'Suggested Orders',

  // Attribution
  poweredBy: 'Powered by evidence-based clinical algorithms',
  source: 'Based on published clinical guidelines',
} as const;

// ============================================================
// EVIDENCE ATTRIBUTION
// ============================================================

export const EVIDENCE_SOURCES = {
  USPSTF: 'U.S. Preventive Services Task Force',
  AHA: 'American Heart Association',
  ADA: 'American Diabetes Association',
  NCCN: 'National Comprehensive Cancer Network',
  CDC: 'Centers for Disease Control and Prevention',
  ACOG: 'American College of Obstetricians and Gynecologists',
  ACP: 'American College of Physicians',
  AAFP: 'American Academy of Family Physicians',
  UpToDate: 'UpToDate Clinical Decision Support',
  ClinicalKey: 'ClinicalKey / Elsevier',
} as const;

export default {
  PRODUCT_NAME,
  PRODUCT_SUBTITLE,
  PRODUCT_TAGLINE,
  CLINICAL_DISCLAIMER,
  CLINICAL_DISCLAIMER_SHORT,
  DIFFERENTIAL_DISCLAIMER,
  RISK_SCORE_DISCLAIMER,
  TREATMENT_DISCLAIMER,
  INTERACTION_DISCLAIMER,
  TERM,
  EVIDENCE_SOURCES,
};
