// =============================================================================
// ATTENDING AI - AI Transparency Disclaimer Templates
// packages/ai-governance/src/disclaimers/templates.ts
//
// CMS HTE requires clear disclaimers distinguishing clinical guidance
// from educational content in conversational AI apps
// =============================================================================

// =============================================================================
// Disclaimer Types
// =============================================================================

export type DisclaimerLevel = 'standard' | 'clinical' | 'emergency' | 'educational';

export interface Disclaimer {
  id: string;
  level: DisclaimerLevel;
  title: string;
  text: string;
  shortText: string;
  machineReadable: {
    contentType: 'clinical-guidance' | 'educational' | 'informational' | 'emergency';
    aiGenerated: boolean;
    modelVersion?: string;
    confidenceScore?: number;
    requiresClinicianReview: boolean;
  };
}

// =============================================================================
// Standard Disclaimers
// =============================================================================

export const DISCLAIMERS: Record<string, Disclaimer> = {
  // Shown on every AI-generated response
  STANDARD_AI: {
    id: 'standard-ai',
    level: 'standard',
    title: 'AI-Generated Content',
    text: 'This information was generated by an AI clinical decision support system. It is intended to support — not replace — clinical judgment. Always consult with your healthcare provider before making medical decisions.',
    shortText: 'AI-assisted — consult your provider',
    machineReadable: {
      contentType: 'informational',
      aiGenerated: true,
      requiresClinicianReview: false,
    },
  },

  // Shown when AI provides clinical guidance
  CLINICAL_GUIDANCE: {
    id: 'clinical-guidance',
    level: 'clinical',
    title: 'Clinical Decision Support',
    text: 'This clinical guidance is generated by AI and is intended for use by healthcare professionals as decision support. It does not constitute a diagnosis or treatment recommendation. The treating physician retains full responsibility for all clinical decisions.',
    shortText: 'Clinical decision support — physician review required',
    machineReadable: {
      contentType: 'clinical-guidance',
      aiGenerated: true,
      requiresClinicianReview: true,
    },
  },

  // Shown for patient-facing educational content
  EDUCATIONAL: {
    id: 'educational',
    level: 'educational',
    title: 'Health Information',
    text: 'This is general health information provided for educational purposes. It is not personalized medical advice and should not be used as a substitute for professional medical consultation, diagnosis, or treatment.',
    shortText: 'Educational information — not medical advice',
    machineReadable: {
      contentType: 'educational',
      aiGenerated: true,
      requiresClinicianReview: false,
    },
  },

  // Shown during emergency detection
  EMERGENCY: {
    id: 'emergency',
    level: 'emergency',
    title: 'Emergency Warning',
    text: 'Our system has detected symptoms that may indicate a medical emergency. If you are experiencing a medical emergency, call 911 immediately. Do not rely on this application for emergency medical care.',
    shortText: 'Possible emergency — call 911 if needed',
    machineReadable: {
      contentType: 'emergency',
      aiGenerated: true,
      requiresClinicianReview: true,
    },
  },

  // Shown when AI analyzes patient health records from CMS networks
  FHIR_DATA_ANALYSIS: {
    id: 'fhir-data-analysis',
    level: 'clinical',
    title: 'Health Record Analysis',
    text: 'This analysis is based on health records retrieved from your authorized healthcare networks. The AI system has reviewed this data to provide insights, but all findings should be verified by your healthcare provider. Your data access is controlled by your consent preferences.',
    shortText: 'Analysis based on your health records — verify with provider',
    machineReadable: {
      contentType: 'clinical-guidance',
      aiGenerated: true,
      requiresClinicianReview: true,
    },
  },

  // Shown for differential diagnosis suggestions
  DIFFERENTIAL_DIAGNOSIS: {
    id: 'differential-diagnosis',
    level: 'clinical',
    title: 'Differential Diagnosis Support',
    text: 'The following differential diagnoses are AI-generated suggestions based on reported symptoms and available clinical data. They are ranked by algorithmic probability, not clinical certainty. The treating physician must independently evaluate each possibility.',
    shortText: 'AI-suggested differentials — requires clinical evaluation',
    machineReadable: {
      contentType: 'clinical-guidance',
      aiGenerated: true,
      requiresClinicianReview: true,
    },
  },
};

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Get the appropriate disclaimer for a given content type.
 */
export function getDisclaimer(contentType: string): Disclaimer {
  switch (contentType) {
    case 'clinical-guidance': return DISCLAIMERS.CLINICAL_GUIDANCE;
    case 'educational': return DISCLAIMERS.EDUCATIONAL;
    case 'emergency': return DISCLAIMERS.EMERGENCY;
    case 'fhir-analysis': return DISCLAIMERS.FHIR_DATA_ANALYSIS;
    case 'differential': return DISCLAIMERS.DIFFERENTIAL_DIAGNOSIS;
    default: return DISCLAIMERS.STANDARD_AI;
  }
}

/**
 * Attach a disclaimer to an AI-generated output.
 */
export function attachDisclaimer<T>(
  output: T,
  disclaimerId: string,
  modelVersion?: string,
  confidenceScore?: number,
): T & { _disclaimer: Disclaimer } {
  const disclaimer = DISCLAIMERS[disclaimerId] || DISCLAIMERS.STANDARD_AI;

  // Attach model version and confidence to machine-readable metadata
  const enriched = {
    ...disclaimer,
    machineReadable: {
      ...disclaimer.machineReadable,
      modelVersion,
      confidenceScore,
    },
  };

  return { ...output, _disclaimer: enriched };
}
