/**
 * INTERACT v4.0 Field Catalog
 *
 * Structured definitions for every field in the INTERACT Transfer Communication Form.
 * Maps each field to its SNF data source, transformation, validation, and priority tier.
 *
 * @see docs/specifications/P16-INTERACT-FIELD-MAPPING.md
 * @see apps/shared/types/interact.types.ts
 */

import type {
  InteractFieldDefinition,
  InteractSectionId,
  InteractValidationRule,
} from '../types/interact.types';

// ---------------------------------------------------------------------------
// Field Catalog
// ---------------------------------------------------------------------------

export const INTERACT_FIELDS: Record<string, InteractFieldDefinition> = {
  // ===== Section A: Patient Identification =====
  patient_full_name: {
    id: 'patient_full_name',
    section: 'PATIENT_IDENTIFICATION',
    label: 'Patient Full Name',
    description: 'Patient last name, first name',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'Patient',
    sourceFields: ['firstName', 'lastName'],
    transformationRule: 'CONCATENATE_LAST_FIRST',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 1,
  },
  date_of_birth: {
    id: 'date_of_birth',
    section: 'PATIENT_IDENTIFICATION',
    label: 'Date of Birth',
    description: 'Patient date of birth',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'Patient',
    sourceFields: ['dateOfBirth'],
    transformationRule: 'ISO_TO_MMDDYYYY',
    validationRule: 'VALID_DATE',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 1,
  },
  gender: {
    id: 'gender',
    section: 'PATIENT_IDENTIFICATION',
    label: 'Gender',
    description: 'Patient gender',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'Patient',
    sourceFields: ['gender'],
    transformationRule: 'DIRECT',
    validationRule: 'ENUM_MATCH',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 3,
  },
  insurance_number: {
    id: 'insurance_number',
    section: 'PATIENT_IDENTIFICATION',
    label: 'Medicare/Medicaid Number',
    description: 'Primary insurance policy number',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'Patient',
    sourceFields: ['insurancePolicyNum'],
    transformationRule: 'DIRECT',
    validationRule: 'NON_EMPTY',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 3,
  },
  insurance_provider: {
    id: 'insurance_provider',
    section: 'PATIENT_IDENTIFICATION',
    label: 'Insurance Provider',
    description: 'Primary insurance provider name',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'Patient',
    sourceFields: ['insuranceProvider'],
    transformationRule: 'DIRECT',
    validationRule: 'NON_EMPTY',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 3,
  },
  snf_facility_name: {
    id: 'snf_facility_name',
    section: 'PATIENT_IDENTIFICATION',
    label: 'SNF Facility Name',
    description: 'Sending skilled nursing facility name',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'Organization',
    sourceFields: ['name'],
    transformationRule: 'DIRECT',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 2,
  },
  snf_phone: {
    id: 'snf_phone',
    section: 'PATIENT_IDENTIFICATION',
    label: 'SNF Phone',
    description: 'Sending facility phone number',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'Organization',
    sourceFields: ['phone'],
    transformationRule: 'DIRECT',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 2,
  },
  attending_physician: {
    id: 'attending_physician',
    section: 'PATIENT_IDENTIFICATION',
    label: 'Attending Physician',
    description: 'SNF attending physician name',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'User',
    sourceFields: ['name'],
    transformationRule: 'DIRECT',
    validationRule: 'CROSS_REFERENCE',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 2,
  },
  transfer_datetime: {
    id: 'transfer_datetime',
    section: 'PATIENT_IDENTIFICATION',
    label: 'Date/Time of Transfer',
    description: 'Transfer initiation timestamp',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'TransferRequest',
    sourceFields: ['createdAt'],
    transformationRule: 'ISO_TO_MMDDYYYY_HHMM',
    validationRule: 'VALID_DATE',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section A',
    priorityTier: 1,
  },

  // ===== Section B: Reason for Transfer =====
  transfer_urgency: {
    id: 'transfer_urgency',
    section: 'TRANSFER_REASON',
    label: 'Transfer Urgency Level',
    description: 'Emergency, Urgent, or Planned',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'TransferRequest',
    sourceFields: ['urgencyLevel'],
    transformationRule: 'DIRECT',
    validationRule: 'ENUM_MATCH',
    interactReference: 'INTERACT 4.0 Section B',
    priorityTier: 1,
  },
  primary_reason: {
    id: 'primary_reason',
    section: 'TRANSFER_REASON',
    label: 'Primary Reason for Transfer',
    description: 'Clinical reason necessitating transfer',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'TransferRequest',
    sourceFields: ['reasonForTransfer'],
    transformationRule: 'DIRECT',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.15(c)(2)(ii)',
    interactReference: 'INTERACT 4.0 Section B',
    priorityTier: 1,
  },
  primary_diagnosis_icd10: {
    id: 'primary_diagnosis_icd10',
    section: 'TRANSFER_REASON',
    label: 'Primary Diagnosis (ICD-10)',
    description: 'ICD-10-CM code for primary transfer diagnosis',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'TransferRequest',
    sourceFields: ['icdCodes'],
    transformationRule: 'JSON_ARRAY_FIRST',
    validationRule: 'VALID_ICD10',
    interactReference: 'INTERACT 4.0 Section B',
    priorityTier: 3,
  },
  early_warning_signs: {
    id: 'early_warning_signs',
    section: 'TRANSFER_REASON',
    label: 'Early Warning Signs Documented',
    description: 'INTERACT-required early warning sign documentation',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'TransferRequest',
    sourceFields: ['metadata.earlyWarningSigns'],
    transformationRule: 'JSON_TO_LIST',
    validationRule: 'NON_EMPTY',
    interactReference: 'INTERACT 4.0 SBAR',
    priorityTier: 3,
  },
  interventions_attempted: {
    id: 'interventions_attempted',
    section: 'TRANSFER_REASON',
    label: 'Interventions Attempted at SNF',
    description: 'Clinical interventions tried before transfer decision',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'TransferRequest',
    sourceFields: ['metadata.interventionsAttempted'],
    transformationRule: 'JSON_ARRAY_WITH_TIMESTAMPS',
    validationRule: 'NON_EMPTY',
    interactReference: 'INTERACT 4.0 Section C',
    priorityTier: 3,
  },
  physician_notification_time: {
    id: 'physician_notification_time',
    section: 'TRANSFER_REASON',
    label: 'Physician Notification Time',
    description: 'When the attending/on-call physician was notified',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'TransferRequest',
    sourceFields: ['metadata.physicianNotifiedAt'],
    transformationRule: 'ISO_TO_MMDDYYYY_HHMM',
    validationRule: 'VALID_DATE',
    interactReference: 'INTERACT 4.0 Section C',
    priorityTier: 3,
  },

  // ===== Section C: Medications =====
  medication_list: {
    id: 'medication_list',
    section: 'MEDICATIONS',
    label: 'Complete Medication List',
    description: 'All active medications from SNF MAR',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'SNFMedication',
    sourceFields: ['medicationName', 'dose', 'doseUnit', 'frequency', 'route'],
    transformationRule: 'AGGREGATE_ACTIVE',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section D',
    priorityTier: 2,
  },
  last_administration_times: {
    id: 'last_administration_times',
    section: 'MEDICATIONS',
    label: 'Last Administration Time per Medication',
    description: 'Most recent administration time for each active medication',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'SNFMedicationAdministration',
    sourceFields: ['administeredTime'],
    transformationRule: 'MOST_RECENT_PER_MEDICATION',
    validationRule: 'VALID_DATE',
    interactReference: 'INTERACT 4.0 Section D',
    priorityTier: 2,
  },
  prn_medications: {
    id: 'prn_medications',
    section: 'MEDICATIONS',
    label: 'PRN Medications',
    description: 'As-needed medications with indications',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'SNFMedication',
    sourceFields: ['medicationName', 'dose', 'prnIndication'],
    transformationRule: 'FILTER_PRN',
    validationRule: 'NON_EMPTY',
    interactReference: 'INTERACT 4.0 Section D',
    priorityTier: 3,
  },
  recent_medication_changes: {
    id: 'recent_medication_changes',
    section: 'MEDICATIONS',
    label: 'Recent Medication Changes (7 Days)',
    description: 'Medications changed within past 7 days',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'SNFMedication',
    sourceFields: ['medicationName', 'dose', 'previousDose', 'lastDoseChange'],
    transformationRule: 'FILTER_RECENT_CHANGES_7D',
    validationRule: 'VALID_DATE',
    cmsReference: 'INTERACT 4.0 Section D',
    interactReference: 'INTERACT 4.0 Section D',
    priorityTier: 3,
  },
  mar_reconciliation_summary: {
    id: 'mar_reconciliation_summary',
    section: 'MEDICATIONS',
    label: 'MAR Reconciliation Summary',
    description: 'Summary of medication reconciliation against hospital formulary',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'MARReconciliation',
    sourceFields: ['totalMedications', 'discrepancyCount', 'criticalDiscrepancyCount'],
    transformationRule: 'RECONCILIATION_SUMMARY',
    validationRule: 'NON_EMPTY',
    interactReference: 'P16 Extension',
    priorityTier: 4,
  },

  // ===== Section D: Allergies =====
  allergy_list: {
    id: 'allergy_list',
    section: 'ALLERGIES',
    label: 'Allergen List',
    description: 'All documented allergies with reactions and severity',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'Allergy',
    sourceFields: ['allergen', 'reactions', 'severity'],
    transformationRule: 'AGGREGATE_ALL',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section E',
    priorityTier: 1,
  },
  nkda_status: {
    id: 'nkda_status',
    section: 'ALLERGIES',
    label: 'NKDA Status',
    description: 'No Known Drug Allergies confirmation',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'Allergy',
    sourceFields: [],
    transformationRule: 'ABSENCE_CHECK',
    validationRule: 'NON_EMPTY',
    interactReference: 'INTERACT 4.0 Section E',
    priorityTier: 1,
  },

  // ===== Section E: Advance Directives =====
  code_status: {
    id: 'code_status',
    section: 'ADVANCE_DIRECTIVES',
    label: 'Code Status',
    description: 'Full Code, DNR, DNR/DNI, CMO, or Limited Interventions',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'AdvanceDirective',
    sourceFields: ['codeStatus'],
    transformationRule: 'DIRECT',
    validationRule: 'ENUM_MATCH',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section F',
    priorityTier: 1,
  },
  directive_document_type: {
    id: 'directive_document_type',
    section: 'ADVANCE_DIRECTIVES',
    label: 'Document Type',
    description: 'POLST, MOLST, Advance Directive, DNR Order, Living Will',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'AdvanceDirective',
    sourceFields: ['documentType'],
    transformationRule: 'DIRECT',
    validationRule: 'ENUM_MATCH',
    interactReference: 'INTERACT 4.0 Section F',
    priorityTier: 3,
  },
  directive_verification: {
    id: 'directive_verification',
    section: 'ADVANCE_DIRECTIVES',
    label: 'Verification Status',
    description: 'When directive was last verified and by whom',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'AdvanceDirective',
    sourceFields: ['verifiedAt', 'verifiedBy'],
    transformationRule: 'VERIFICATION_STATUS',
    validationRule: 'FRESHNESS',
    validationParams: { maxAgeDays: 90 },
    interactReference: 'INTERACT 4.0 Section F',
    priorityTier: 3,
  },

  // ===== Section F: Functional Status =====
  barthel_index: {
    id: 'barthel_index',
    section: 'FUNCTIONAL_STATUS',
    label: 'Barthel Index Score',
    description: 'Barthel Index of Activities of Daily Living (0-100)',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'FunctionalStatusAssessment',
    sourceFields: ['totalScore', 'subscores'],
    transformationRule: 'INSTRUMENT_SCORE_WITH_INTERPRETATION',
    validationRule: 'NUMERIC_RANGE',
    validationParams: { min: 0, max: 100 },
    interactReference: 'P16 Extension',
    priorityTier: 4,
  },
  katz_adl: {
    id: 'katz_adl',
    section: 'FUNCTIONAL_STATUS',
    label: 'Katz ADL Score',
    description: 'Katz Index of Independence in ADLs (0-6)',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'FunctionalStatusAssessment',
    sourceFields: ['totalScore'],
    transformationRule: 'INSTRUMENT_SCORE_WITH_INTERPRETATION',
    validationRule: 'NUMERIC_RANGE',
    validationParams: { min: 0, max: 6 },
    interactReference: 'P16 Extension',
    priorityTier: 4,
  },
  morse_fall_risk: {
    id: 'morse_fall_risk',
    section: 'FUNCTIONAL_STATUS',
    label: 'Morse Fall Risk Score',
    description: 'Morse Fall Scale (0-125)',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'FunctionalStatusAssessment',
    sourceFields: ['totalScore', 'subscores'],
    transformationRule: 'INSTRUMENT_SCORE_WITH_INTERPRETATION',
    validationRule: 'NUMERIC_RANGE',
    validationParams: { min: 0, max: 125 },
    interactReference: 'P16 Extension',
    priorityTier: 4,
  },
  cognitive_status: {
    id: 'cognitive_status',
    section: 'FUNCTIONAL_STATUS',
    label: 'Cognitive Status',
    description: 'Baseline cognitive status assessment',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'FunctionalStatusAssessment',
    sourceFields: ['cognitiveStatus'],
    transformationRule: 'DIRECT',
    validationRule: 'ENUM_MATCH',
    interactReference: 'INTERACT 4.0 Section G',
    priorityTier: 4,
  },
  transfer_assistance_level: {
    id: 'transfer_assistance_level',
    section: 'FUNCTIONAL_STATUS',
    label: 'Transfer Assistance Level',
    description: 'Level of assistance needed for transfers',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'FunctionalStatusAssessment',
    sourceFields: ['transferAssistance'],
    transformationRule: 'DIRECT',
    validationRule: 'ENUM_MATCH',
    interactReference: 'INTERACT 4.0 Section G',
    priorityTier: 4,
  },

  // ===== Section G: Wound Assessment =====
  wound_inventory: {
    id: 'wound_inventory',
    section: 'WOUND_STATUS',
    label: 'Wound Inventory',
    description: 'All documented wounds with staging and dimensions',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'WoundAssessment',
    sourceFields: ['location', 'woundType', 'stage', 'length', 'width', 'depth'],
    transformationRule: 'AGGREGATE_ALL',
    validationRule: 'NON_EMPTY',
    cmsReference: 'CMS F686',
    interactReference: 'INTERACT 4.0 Section H',
    priorityTier: 4,
  },
  braden_score: {
    id: 'braden_score',
    section: 'WOUND_STATUS',
    label: 'Braden Scale Score',
    description: 'Pressure injury risk assessment (6-23)',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'WoundAssessment',
    sourceFields: ['bradenScore', 'bradenSubscores'],
    transformationRule: 'INSTRUMENT_SCORE_WITH_INTERPRETATION',
    validationRule: 'NUMERIC_RANGE',
    validationParams: { min: 6, max: 23 },
    cmsReference: 'CMS F686',
    interactReference: 'P16 Extension',
    priorityTier: 4,
  },

  // ===== Section H: Isolation Precautions =====
  isolation_status: {
    id: 'isolation_status',
    section: 'ISOLATION_PRECAUTIONS',
    label: 'Active Isolation Precautions',
    description: 'Whether patient has active isolation precautions',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'IsolationPrecaution',
    sourceFields: ['status'],
    transformationRule: 'BOOLEAN_ANY_ACTIVE',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.80',
    interactReference: 'INTERACT 4.0 Section I',
    priorityTier: 1,
  },
  isolation_organism: {
    id: 'isolation_organism',
    section: 'ISOLATION_PRECAUTIONS',
    label: 'Causative Organism',
    description: 'Specific organism requiring isolation',
    required: false,
    requiredInEmergency: true,
    sourceModel: 'IsolationPrecaution',
    sourceFields: ['organism', 'organismCode'],
    transformationRule: 'DIRECT',
    validationRule: 'CONDITIONAL_REQUIRED',
    validationParams: { condition: 'isolation_status', value: true },
    cmsReference: '42 CFR 483.80',
    interactReference: 'INTERACT 4.0 Section I',
    priorityTier: 1,
  },
  isolation_precaution_type: {
    id: 'isolation_precaution_type',
    section: 'ISOLATION_PRECAUTIONS',
    label: 'Precaution Type',
    description: 'Contact, Droplet, Airborne, etc.',
    required: false,
    requiredInEmergency: true,
    sourceModel: 'IsolationPrecaution',
    sourceFields: ['precautionType'],
    transformationRule: 'DIRECT',
    validationRule: 'CONDITIONAL_REQUIRED',
    validationParams: { condition: 'isolation_status', value: true },
    interactReference: 'INTERACT 4.0 Section I',
    priorityTier: 1,
  },
  culture_date: {
    id: 'culture_date',
    section: 'ISOLATION_PRECAUTIONS',
    label: 'Most Recent Culture Date',
    description: 'Date of most recent positive culture',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'IsolationPrecaution',
    sourceFields: ['cultureDate'],
    transformationRule: 'ISO_TO_MMDDYYYY',
    validationRule: 'VALID_DATE',
    interactReference: 'P16 Extension',
    priorityTier: 3,
  },

  // ===== Section I: Diagnostics =====
  recent_labs: {
    id: 'recent_labs',
    section: 'DIAGNOSTICS',
    label: 'Lab Results (Last 30 Days)',
    description: 'All lab results from past 30 days',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'LabResult',
    sourceFields: ['testName', 'result', 'units', 'referenceRange', 'createdAt'],
    transformationRule: 'FILTER_BY_DATE_RANGE_30D',
    validationRule: 'FRESHNESS',
    validationParams: { maxAgeDays: 30 },
    interactReference: 'INTERACT 4.0 Section J',
    priorityTier: 3,
  },
  most_recent_vitals: {
    id: 'most_recent_vitals',
    section: 'DIAGNOSTICS',
    label: 'Most Recent Vital Signs',
    description: 'Latest vital signs reading',
    required: true,
    requiredInEmergency: true,
    sourceModel: 'VitalSigns',
    sourceFields: [
      'bloodPressureSystolic', 'bloodPressureDiastolic',
      'heartRate', 'respiratoryRate', 'temperature',
      'oxygenSaturation', 'weight',
    ],
    transformationRule: 'MOST_RECENT',
    validationRule: 'NON_EMPTY',
    cmsReference: '42 CFR 483.15(c)(2)(iii)',
    interactReference: 'INTERACT 4.0 Section J',
    priorityTier: 2,
  },

  // ===== Section J: Transfer Logistics =====
  receiving_hospital: {
    id: 'receiving_hospital',
    section: 'TRANSFER_LOGISTICS',
    label: 'Receiving Hospital',
    description: 'Destination hospital name',
    required: true,
    requiredInEmergency: false,
    sourceModel: 'Organization',
    sourceFields: ['name'],
    transformationRule: 'DIRECT',
    validationRule: 'CROSS_REFERENCE',
    interactReference: 'INTERACT 4.0 Section K',
    priorityTier: 3,
  },
  ppr_flag: {
    id: 'ppr_flag',
    section: 'TRANSFER_LOGISTICS',
    label: 'PPR Risk Flag',
    description: 'Potentially Preventable Readmission risk indicator',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'TransferRequest',
    sourceFields: ['pprFlagged', 'pprDiagnosisCodes'],
    transformationRule: 'PPR_FLAG_FORMAT',
    validationRule: 'NON_EMPTY',
    cmsReference: 'CMS SNF QRP',
    interactReference: 'P16 Extension',
    priorityTier: 4,
  },
  interact_compliance_score: {
    id: 'interact_compliance_score',
    section: 'TRANSFER_LOGISTICS',
    label: 'INTERACT Compliance Score',
    description: 'Percentage of required INTERACT fields completed',
    required: false,
    requiredInEmergency: false,
    sourceModel: 'TransferRequest',
    sourceFields: ['metadata.interactComplianceScore'],
    transformationRule: 'PERCENTAGE',
    validationRule: 'NUMERIC_RANGE',
    validationParams: { min: 0, max: 100 },
    interactReference: 'P16 Extension',
    priorityTier: 4,
  },
};

// ---------------------------------------------------------------------------
// Section Metadata
// ---------------------------------------------------------------------------

export interface InteractSectionMeta {
  id: InteractSectionId;
  label: string;
  interactFormSection: string;
  requiredInEmergency: boolean;
  description: string;
  fieldCount: number;
}

export const INTERACT_SECTIONS: InteractSectionMeta[] = [
  {
    id: 'PATIENT_IDENTIFICATION',
    label: 'Patient Identification',
    interactFormSection: 'Section A',
    requiredInEmergency: true,
    description: 'Patient demographics, facility info, physician',
    fieldCount: 15,
  },
  {
    id: 'TRANSFER_REASON',
    label: 'Reason for Transfer',
    interactFormSection: 'Section B',
    requiredInEmergency: true,
    description: 'Urgency, diagnosis, symptoms, interventions tried',
    fieldCount: 11,
  },
  {
    id: 'MEDICATIONS',
    label: 'Current Medications',
    interactFormSection: 'Section C/D',
    requiredInEmergency: true,
    description: 'Full MAR, PRN, holds, recent changes, reconciliation',
    fieldCount: 10,
  },
  {
    id: 'ALLERGIES',
    label: 'Allergies',
    interactFormSection: 'Section E',
    requiredInEmergency: true,
    description: 'Allergens, reactions, severity, NKDA status',
    fieldCount: 4,
  },
  {
    id: 'ADVANCE_DIRECTIVES',
    label: 'Advance Directives',
    interactFormSection: 'Section F',
    requiredInEmergency: true,
    description: 'Code status, POLST, treatment preferences',
    fieldCount: 10,
  },
  {
    id: 'FUNCTIONAL_STATUS',
    label: 'Functional Status',
    interactFormSection: 'Section G',
    requiredInEmergency: false,
    description: 'ADL scores, fall risk, cognitive baseline, mobility',
    fieldCount: 10,
  },
  {
    id: 'WOUND_STATUS',
    label: 'Skin/Wound Assessment',
    interactFormSection: 'Section H',
    requiredInEmergency: false,
    description: 'Wound inventory, staging, dimensions, Braden score',
    fieldCount: 15,
  },
  {
    id: 'ISOLATION_PRECAUTIONS',
    label: 'Isolation Precautions',
    interactFormSection: 'Section I',
    requiredInEmergency: true,
    description: 'Active precautions, organism, PPE, room requirements',
    fieldCount: 10,
  },
  {
    id: 'DIAGNOSTICS',
    label: 'Recent Diagnostics',
    interactFormSection: 'Section J',
    requiredInEmergency: true,
    description: 'Labs, imaging, vital signs trends',
    fieldCount: 5,
  },
  {
    id: 'TRANSFER_LOGISTICS',
    label: 'Transfer Logistics',
    interactFormSection: 'Section K',
    requiredInEmergency: false,
    description: 'Receiving hospital, transport, PPR flag, compliance',
    fieldCount: 12,
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function getFieldsBySection(
  section: InteractSectionId
): InteractFieldDefinition[] {
  return Object.values(INTERACT_FIELDS).filter((f) => f.section === section);
}

export function getEmergencyFields(): InteractFieldDefinition[] {
  return Object.values(INTERACT_FIELDS).filter((f) => f.requiredInEmergency);
}

export function getFieldsByPriorityTier(
  tier: 1 | 2 | 3 | 4
): InteractFieldDefinition[] {
  return Object.values(INTERACT_FIELDS).filter((f) => f.priorityTier === tier);
}

export function getRequiredFields(): InteractFieldDefinition[] {
  return Object.values(INTERACT_FIELDS).filter((f) => f.required);
}

export function calculateComplianceScore(
  completedFieldIds: Set<string>
): number {
  const required = getRequiredFields();
  if (required.length === 0) return 100;
  const completed = required.filter((f) => completedFieldIds.has(f.id));
  return Math.round((completed.length / required.length) * 100);
}
