#!/usr/bin/env node
// ============================================================
// ATTENDING AI - Development Startup Script
// scripts/dev-setup.js
//
// Complete development environment setup:
// 1. Checks prerequisites (Node, npm, Docker)
// 2. Starts PostgreSQL database (Docker)
// 3. Runs Prisma migrations
// 4. Seeds the database
// 5. Starts all services
//
// Usage: node scripts/dev-setup.js
//        npm run dev:setup
// ============================================================

const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

// Configuration
const CONFIG = {
  dbName: 'attending_dev',
  dbUser: 'postgres',
  dbPassword: 'attending',
  dbPort: 5432,
  dbContainerName: 'attending-postgres',
  providerPort: 3000,
  patientPort: 3001,
  wsPort: 3003,
};

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

function log(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function logStep(step, message) {
  console.log(`\n${colors.cyan}[Step ${step}]${colors.reset} ${colors.bright}${message}${colors.reset}`);
}

function logSuccess(message) {
  console.log(`${colors.green}✅ ${message}${colors.reset}`);
}

function logWarning(message) {
  console.log(`${colors.yellow}⚠️  ${message}${colors.reset}`);
}

function logError(message) {
  console.log(`${colors.red}❌ ${message}${colors.reset}`);
}

function execCommand(command, options = {}) {
  try {
    const result = execSync(command, {
      encoding: 'utf8',
      stdio: options.silent ? 'pipe' : 'inherit',
      ...options,
    });
    return { success: true, output: result };
  } catch (error) {
    return { success: false, error: error.message };
  }
}

function checkCommand(command) {
  try {
    execSync(`${command} --version`, { encoding: 'utf8', stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

async function prompt(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

async function main() {
  console.log(`
${colors.blue}╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║     🏥 ATTENDING AI - Development Setup                   ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝${colors.reset}
  `);

  // =====================================================
  // Step 1: Check Prerequisites
  // =====================================================
  logStep(1, 'Checking prerequisites...');

  const prerequisites = [
    { name: 'Node.js', command: 'node', minVersion: '18.0.0' },
    { name: 'npm', command: 'npm', minVersion: '9.0.0' },
    { name: 'Docker', command: 'docker', optional: true },
  ];

  let missingRequired = false;
  let dockerAvailable = false;

  for (const prereq of prerequisites) {
    if (checkCommand(prereq.command)) {
      logSuccess(`${prereq.name} is installed`);
      if (prereq.command === 'docker') dockerAvailable = true;
    } else if (prereq.optional) {
      logWarning(`${prereq.name} not found (optional)`);
    } else {
      logError(`${prereq.name} is required but not installed`);
      missingRequired = true;
    }
  }

  if (missingRequired) {
    logError('Please install missing prerequisites and try again.');
    process.exit(1);
  }

  // =====================================================
  // Step 2: Create/Check Environment File
  // =====================================================
  logStep(2, 'Setting up environment...');

  const envPath = path.join(process.cwd(), '.env');
  const envContent = `# ATTENDING AI - Development Environment
# Generated by dev-setup.js on ${new Date().toISOString()}

# Database
DATABASE_URL="postgresql://${CONFIG.dbUser}:${CONFIG.dbPassword}@localhost:${CONFIG.dbPort}/${CONFIG.dbName}"

# Authentication
NEXTAUTH_SECRET="dev-secret-change-in-production-${Date.now()}"
NEXTAUTH_URL="http://localhost:${CONFIG.providerPort}"

# WebSocket
NEXT_PUBLIC_WS_URL="http://localhost:${CONFIG.wsPort}"
WEBSOCKET_URL="http://localhost:${CONFIG.wsPort}"

# Provider Portal API (for patient portal to call)
PROVIDER_API_URL="http://localhost:${CONFIG.providerPort}"

# Development
NODE_ENV="development"
`;

  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, envContent);
    logSuccess('Created .env file');
  } else {
    logSuccess('.env file already exists');
  }

  // =====================================================
  // Step 3: Start PostgreSQL Database
  // =====================================================
  logStep(3, 'Starting PostgreSQL database...');

  if (dockerAvailable) {
    // Check if container exists
    const checkContainer = execCommand(
      `docker ps -a --filter name=${CONFIG.dbContainerName} --format "{{.Names}}"`,
      { silent: true }
    );

    if (checkContainer.output?.includes(CONFIG.dbContainerName)) {
      // Container exists, check if running
      const checkRunning = execCommand(
        `docker ps --filter name=${CONFIG.dbContainerName} --format "{{.Names}}"`,
        { silent: true }
      );

      if (checkRunning.output?.includes(CONFIG.dbContainerName)) {
        logSuccess('PostgreSQL container is already running');
      } else {
        log('Starting existing PostgreSQL container...');
        execCommand(`docker start ${CONFIG.dbContainerName}`);
        logSuccess('PostgreSQL container started');
      }
    } else {
      // Create new container
      log('Creating new PostgreSQL container...');
      const createResult = execCommand(
        `docker run -d --name ${CONFIG.dbContainerName} ` +
        `-e POSTGRES_PASSWORD=${CONFIG.dbPassword} ` +
        `-e POSTGRES_DB=${CONFIG.dbName} ` +
        `-p ${CONFIG.dbPort}:5432 ` +
        `postgres:15`
      );

      if (createResult.success) {
        logSuccess('PostgreSQL container created');
        log('Waiting for database to be ready...');
        await new Promise(resolve => setTimeout(resolve, 5000));
      } else {
        logError('Failed to create PostgreSQL container');
        log('You may need to start PostgreSQL manually');
      }
    }
  } else {
    logWarning('Docker not available - please ensure PostgreSQL is running on port 5432');
    const answer = await prompt('Is PostgreSQL running? (y/n): ');
    if (answer.toLowerCase() !== 'y') {
      logError('Please start PostgreSQL and run this script again.');
      process.exit(1);
    }
  }

  // =====================================================
  // Step 4: Install Dependencies
  // =====================================================
  logStep(4, 'Installing dependencies...');

  const installResult = execCommand('npm install');
  if (installResult.success) {
    logSuccess('Dependencies installed');
  } else {
    logWarning('Some dependencies may have failed to install');
  }

  // =====================================================
  // Step 5: Generate Prisma Client
  // =====================================================
  logStep(5, 'Generating Prisma client...');

  const prismaResult = execCommand('npx prisma generate');
  if (prismaResult.success) {
    logSuccess('Prisma client generated');
  } else {
    logError('Failed to generate Prisma client');
  }

  // =====================================================
  // Step 6: Push Database Schema
  // =====================================================
  logStep(6, 'Pushing database schema...');

  const pushResult = execCommand('npx prisma db push');
  if (pushResult.success) {
    logSuccess('Database schema pushed');
  } else {
    logError('Failed to push database schema');
    logWarning('You may need to check your DATABASE_URL in .env');
  }

  // =====================================================
  // Step 7: Seed Database
  // =====================================================
  logStep(7, 'Seeding database with clinical data...');

  const seedResult = execCommand('npm run db:seed');
  if (seedResult.success) {
    logSuccess('Database seeded with clinical scenarios');
  } else {
    logWarning('Database seeding may have failed - check manually');
  }

  // =====================================================
  // Step 8: Start Development Servers
  // =====================================================
  logStep(8, 'Starting development servers...');

  console.log(`
${colors.green}╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║     🎉 Setup Complete!                                     ║
║                                                           ║
╠═══════════════════════════════════════════════════════════╣
║                                                           ║
║     Provider Portal:  http://localhost:${CONFIG.providerPort}              ║
║     Patient Portal:   http://localhost:${CONFIG.patientPort}              ║
║     WebSocket Server: http://localhost:${CONFIG.wsPort}              ║
║     Prisma Studio:    npx prisma studio                   ║
║                                                           ║
╠═══════════════════════════════════════════════════════════╣
║                                                           ║
║     To start the servers manually:                        ║
║                                                           ║
║     npm run dev:provider   (Provider Portal)              ║
║     npm run dev:patient    (Patient Portal)               ║
║     npm run dev            (Both)                         ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝${colors.reset}
  `);

  const startServers = await prompt('\nStart development servers now? (y/n): ');

  if (startServers.toLowerCase() === 'y') {
    log('\nStarting servers... (Press Ctrl+C to stop)\n', colors.cyan);
    
    // Start both servers concurrently
    const devProcess = spawn('npm', ['run', 'dev'], {
      stdio: 'inherit',
      shell: true,
    });

    devProcess.on('error', (error) => {
      logError(`Failed to start servers: ${error.message}`);
    });
  } else {
    log('\nRun "npm run dev" when ready to start the servers.\n', colors.cyan);
  }
}

// Run the setup
main().catch((error) => {
  logError(`Setup failed: ${error.message}`);
  process.exit(1);
});
